import { getSession } from 'next-auth/client'
import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import InputBox from '../components/InputBox'
import Login from '../components/Login'
import SideBar from '../components/SideBar'

export default function Home({session}) {
  
  if(!session) return <Login />
  
  return (
    <div className="h-screen bg-gray-100 overflow-hidden" >
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header  />

      <main className='flex'>
        <SideBar />
        <Feed />
       
      </main>
      
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)
  // const posts = await res.json()

  return {
    props: {
      session,
    },
  }
}
